--XTablas
DROP TABLE AMENAZAS CASCADE CONSTRAINTS PURGE;
DROP TABLE IMPACTOS CASCADE CONSTRAINTS PURGE;
DROP TABLE ECOSISTEMAS CASCADE CONSTRAINTS PURGE;
DROP TABLE UBICACIONES CASCADE CONSTRAINTS PURGE;
DROP TABLE PARQUES_NATURALES CASCADE CONSTRAINTS PURGE;
DROP TABLE PUBLICACIONES_CIENTIFICAS CASCADE CONSTRAINTS PURGE;
DROP TABLE SERVICIOS CASCADE CONSTRAINTS PURGE;
DROP TABLE ACTIVIDADES_PERMITIDAS CASCADE CONSTRAINTS PURGE;
DROP TABLE RESERVAS CASCADE CONSTRAINTS PURGE;
DROP TABLE PERSONAS CASCADE CONSTRAINTS PURGE;
DROP TABLE NINIOS CASCADE CONSTRAINTS PURGE;
DROP TABLE ADULTOS CASCADE CONSTRAINTS PURGE;
DROP TABLE CONTACTOS_PARQUE CASCADE CONSTRAINTS PURGE;
DROP TABLE PAISES CASCADE CONSTRAINTS PURGE;
DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS PURGE;
DROP TABLE ESPECIES_ANIMALES CASCADE CONSTRAINTS PURGE;
DROP TABLE ESPECIES_PLANTAS CASCADE CONSTRAINTS PURGE;
DROP TABLE AMENAZAS_POR_PARQUE CASCADE CONSTRAINTS PURGE;
DROP TABLE UBICACIONES_POR_PARQUE CASCADE CONSTRAINTS PURGE;
DROP TABLE ESPECIES_AFECTADAS CASCADE CONSTRAINTS PURGE;
DROP TABLE EQUIPOS_BASICOS CASCADE CONSTRAINTS PURGE;
DROP TABLE ACTIVIDADES_POR_PARQUE CASCADE CONSTRAINTS PURGE;


--- Tablas
CREATE TABLE PARQUES_NATURALES (
  CODIGO VARCHAR2(50) NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  HORA_APERTURA DATE NOT NULL,
  HORA_CIERRE DATE NOT NULL,
  CANT_TRABAJADORES NUMBER NOT NULL,
  FECHA_REGISTRO DATE NOT NULL,
  VALOR_INGRESO_ADULTOS NUMBER,
  VALOR_INGRESO_NINOS NUMBER,
  ESTADO VARCHAR2(50) NOT NULL
);

CREATE TABLE AMENAZAS (
  CODIGO VARCHAR2(50) NOT NULL,
  ESTADO VARCHAR2(50) NOT NULL,
  GRAVEDAD VARCHAR2(50) NOT NULL,
  TIPO VARCHAR2(50) NOT NULL,
  FECHA_DETECCION DATE NOT NULL,
  FECHA_MITIGACION DATE
);

CREATE TABLE AMENAZAS_POR_PARQUE (
  CODIGO_PARQUE VARCHAR2(50) NOT NULL,
  CODIGO_AMENAZA VARCHAR2(50) NOT NULL
);

CREATE TABLE IMPACTOS (
  CODIGO_AMENAZA VARCHAR2(50) NOT NULL,
  DESCRIPCION VARCHAR2(500),
  ACCION_MITIGACION VARCHAR2(50) NOT NULL,
  SEVERIDAD VARCHAR2(50) NOT NULL
);

CREATE TABLE ESPECIES_AFECTADAS (
  CODIGO_ESPECIE VARCHAR2(50) NOT NULL,
  NOMBRE_ESPECIE VARCHAR2(50) NOT NULL,
  CODIGO_AMENAZA VARCHAR2(50) NOT NULL
);

CREATE TABLE UBICACIONES (
  LATITUD NUMBER NOT NULL,
  LONGITUD NUMBER NOT NULL,
  TAMANO NUMBER NOT NULL
);

CREATE TABLE PAISES (
  ID_PAIS VARCHAR2(50) NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  LATITUD NUMBER NOT NULL,
  LONGITUD NUMBER NOT NULL
);

CREATE TABLE DEPARTAMENTOS (
  ID_DEPARTAMENTO VARCHAR2(50) NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  LATITUD NUMBER NOT NULL,
  LONGITUD NUMBER NOT NULL
);

CREATE TABLE UBICACIONES_POR_PARQUE (
  CODIGO_PARQUE VARCHAR2(50) NOT NULL,
  LATITUD NUMBER NOT NULL,
  LONGITUD NUMBER NOT NULL
);

CREATE TABLE CONTACTOS_PARQUE (
  CODIGO_PARQUE VARCHAR2(50) NOT NULL,
  CONTACTO VARCHAR2(50) NOT NULL
);

CREATE TABLE ECOSISTEMAS (
  CODIGO VARCHAR2(50) NOT NULL,
  NOMBRE_ECOSISTEMA VARCHAR2(50) NOT NULL,
  CLIMA VARCHAR2(50) NOT NULL,
  CODIGO_PARQUE VARCHAR2(50)
);

CREATE TABLE ESPECIES_ANIMALES ( 
  ID VARCHAR2(50) NOT NULL,
  NOMBRE_CIENTIFICO VARCHAR2(50) NOT NULL,
  NOMBRE_COMUN VARCHAR2(50) NOT NULL,
  CODIGO_ECOSISTEMA VARCHAR2(50) NOT NULL
);

CREATE TABLE ESPECIES_PLANTAS (
  ID VARCHAR2(50) NOT NULL,
  NOMBRE_CIENTIFICO VARCHAR2(50) NOT NULL,
  NOMBRE_COMUN VARCHAR2(50) NOT NULL,
  CODIGO_ECOSISTEMA VARCHAR2(50) NOT NULL
);

CREATE TABLE PUBLICACIONES_CIENTIFICAS (
  ID VARCHAR2(50) NOT NULL,
  CODIGO_PARQUE VARCHAR2(50) NOT NULL,
  TITULO VARCHAR2(50) NOT NULL,
  FECHA_PUBLICACION DATE NOT NULL,
  RESUMEN VARCHAR2(50),
  PALABRA_CLAVE VARCHAR2(50) NOT NULL,
  ENLACE VARCHAR2(50) NOT NULL,
  TIPO_PUBLICACION VARCHAR2(50) NOT NULL,
  FECHA_REGISTRO DATE NOT NULL,
  AUTOR VARCHAR2(50) NOT NULL
);

CREATE TABLE ACTIVIDADES_PERMITIDAS (
  ID VARCHAR2(50) NOT NULL,
  DESCRIPCION_ACTIVIDAD VARCHAR2(500) NOT NULL,
  TIPO_DE_ACTIVIDAD VARCHAR2(50) NOT NULL
);

CREATE TABLE EQUIPOS_BASICOS (
  ID VARCHAR2(50) NOT NULL,
  ID_ACTIVIDAD VARCHAR2(50) NOT NULL,
  NOMBRE_EQUIPO VARCHAR2(50) NOT NULL
);

CREATE TABLE ACTIVIDADES_POR_PARQUE(
  ID_PARQUE VARCHAR2(50) NOT NULL,
  ID_ACTIVIDAD VARCHAR2(50) NOT NULL
);

CREATE TABLE SERVICIOS (
  ID VARCHAR2(50) NOT NULL,
  ID_ACTIVIDAD VARCHAR2(50) NOT NULL,
  DESCRIPCION VARCHAR2(50),
  TIPO_SERVICIO VARCHAR2(50) NOT NULL,
  RESPONSABLE VARCHAR2(50) NOT NULL,
  MAYOR_DE_EDAD NUMBER(1) NOT NULL,
  PRECIO_DIA NUMBER NOT NULL,
  PRECIO_PERSONA NUMBER NOT NULL
);

CREATE TABLE RESERVAS (
  NUMERO VARCHAR2(50) NOT NULL,
  ID_SERVICIO VARCHAR2(50) NOT NULL,
  ID_ADULTO VARCHAR2(50) NOT NULL,
  FECHA_RESERVACION DATE NOT NULL,
  PAGADO NUMBER NOT NULL,
  CANTIDAD_PERSONAS NUMBER NOT NULL,
  ESTADO VARCHAR2(50) NOT NULL,
  FECHA_ASISTENCIA DATE NOT NULL,
  FECHA_FIN DATE NOT NULL,
  PRECIO_TOTAL NUMBER NOT NULL
);

CREATE TABLE PERSONAS (
  ID_USUARIO VARCHAR2(50) NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  GENERO VARCHAR2(50) NOT NULL,
  DOCUMENTO_IDENTIFICACION VARCHAR2(50) NOT NULL,
  TIPO_DOCUMENTO VARCHAR2(50) NOT NULL
);

CREATE TABLE NINIOS (
  ID_USUARIO VARCHAR2(50) NOT NULL,
  RH VARCHAR2(50) NOT NULL,
  RESPONSABLE VARCHAR2(50) NOT NULL,
  CARNET_VACUNAS VARCHAR2(500) NOT NULL,
  ESTATURA NUMBER(3,2) NOT NULL,
  CONSENTIMIENTO VARCHAR2(50) NOT NULL
);


CREATE TABLE ADULTOS (
  ID_USUARIO VARCHAR2(50) NOT NULL,
  PAIS_RESIDENCIA VARCHAR2(50) NOT   NULL,
  CONTACTO VARCHAR2(50) NOT NULL,
  CORREO VARCHAR2(50) NOT NULL
);


-- Primarias
ALTER TABLE PARQUES_NATURALES
ADD CONSTRAINT PK_PARQUES_NATURALES PRIMARY KEY (CODIGO);

ALTER TABLE AMENAZAS
ADD CONSTRAINT PK_AMENAZAS PRIMARY KEY (CODIGO);

ALTER TABLE AMENAZAS_POR_PARQUE
ADD CONSTRAINT PK_AMENAZAS_POR_PARQUE PRIMARY KEY (CODIGO_PARQUE, CODIGO_AMENAZA);

ALTER TABLE IMPACTOS
ADD CONSTRAINT PK_IMPACTOS PRIMARY KEY (CODIGO_AMENAZA);

ALTER TABLE ESPECIES_AFECTADAS
ADD CONSTRAINT PK_ESPECIES_AFECTADAS PRIMARY KEY (CODIGO_ESPECIE);

ALTER TABLE UBICACIONES
ADD CONSTRAINT PK_UBICACIONES PRIMARY KEY (LATITUD, LONGITUD);

ALTER TABLE PAISES
ADD CONSTRAINT PK_PAISES PRIMARY KEY (ID_PAIS);

ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY (ID_DEPARTAMENTO);

ALTER TABLE UBICACIONES_POR_PARQUE
ADD CONSTRAINT PK_UBICACIONES_POR_PARQUE PRIMARY KEY (CODIGO_PARQUE, LATITUD, LONGITUD);

ALTER TABLE CONTACTOS_PARQUE
ADD CONSTRAINT PK_CONTACTOS_PARQUE PRIMARY KEY (CONTACTO);

ALTER TABLE ECOSISTEMAS
ADD CONSTRAINT PK_ECOSISTEMAS PRIMARY KEY (CODIGO);

ALTER TABLE ESPECIES_ANIMALES
ADD CONSTRAINT PK_ESPECIES_ANIMALES PRIMARY KEY (ID);

ALTER TABLE ESPECIES_PLANTAS
ADD CONSTRAINT PK_ESPECIES_PLANTAS PRIMARY KEY (ID);

ALTER TABLE PUBLICACIONES_CIENTIFICAS
ADD CONSTRAINT PK_PUBLICACIONES_CIENTIFICAS PRIMARY KEY (ID);

ALTER TABLE ACTIVIDADES_PERMITIDAS
ADD CONSTRAINT PK_ACTIVIDADES_PERMITIDAS PRIMARY KEY (ID);

ALTER TABLE EQUIPOS_BASICOS
ADD CONSTRAINT PK_EQUIPOS_BASICOS PRIMARY KEY (ID);

ALTER TABLE ACTIVIDADES_POR_PARQUE
ADD CONSTRAINT PK_ACTIVIDADES_POR_PARQUE PRIMARY KEY (ID_PARQUE, ID_ACTIVIDAD);

ALTER TABLE SERVICIOS
ADD CONSTRAINT PK_SERVICIOS PRIMARY KEY (ID);

ALTER TABLE RESERVAS
ADD CONSTRAINT PK_RESERVAS PRIMARY KEY (NUMERO);

ALTER TABLE PERSONAS
ADD CONSTRAINT PK_PERSONAS PRIMARY KEY (ID_USUARIO);

ALTER TABLE ADULTOS
ADD CONSTRAINT PK_ADULTOS PRIMARY KEY (ID_USUARIO);

ALTER TABLE NINIOS
ADD CONSTRAINT PK_NINIOS PRIMARY KEY (ID_USUARIO);

-- Foraneas
ALTER TABLE NINIOS ADD CONSTRAINT FK_RESPONSABLE
FOREIGN KEY(RESPONSABLE ) REFERENCES ADULTOS(ID_USUARIO);

ALTER TABLE AMENAZAS_POR_PARQUE
ADD CONSTRAINT FK_AMENAZAS_POR_PARQUE
FOREIGN KEY (CODIGO_PARQUE) REFERENCES PARQUES_NATURALES(CODIGO);

ALTER TABLE AMENAZAS_POR_PARQUE
ADD CONSTRAINT FK_AMENAZAS_POR_PARQUE_2
FOREIGN KEY (CODIGO_AMENAZA) REFERENCES AMENAZAS(CODIGO);

ALTER TABLE IMPACTOS
ADD CONSTRAINT FK_IMPACTOS_AMENAZAS
FOREIGN KEY (CODIGO_AMENAZA) REFERENCES AMENAZAS(CODIGO);

ALTER TABLE ESPECIES_AFECTADAS
ADD CONSTRAINT FK_ESPECIES_AFECTADAS_AMENAZAS
FOREIGN KEY (CODIGO_AMENAZA) REFERENCES AMENAZAS(CODIGO);

ALTER TABLE UBICACIONES_POR_PARQUE
ADD CONSTRAINT FK_UBICACIONES_POR_PARQUE_PARQUES_NATURALES
FOREIGN KEY (CODIGO_PARQUE) REFERENCES PARQUES_NATURALES(CODIGO);

ALTER TABLE CONTACTOS_PARQUE
ADD CONSTRAINT FK_CONTACTOS_PARQUE_PARQUES_NATURALES
FOREIGN KEY (CODIGO_PARQUE) REFERENCES PARQUES_NATURALES(CODIGO);

ALTER TABLE ECOSISTEMAS
ADD CONSTRAINT FK_ECOSISTEMAS_PARQUES_NATURALES
FOREIGN KEY (CODIGO_PARQUE) REFERENCES PARQUES_NATURALES(CODIGO);

ALTER TABLE ESPECIES_ANIMALES
ADD CONSTRAINT FK_ESPECIES_ANIMALES_ECOSISTEMAS
FOREIGN KEY (CODIGO_ECOSISTEMA) REFERENCES ECOSISTEMAS(CODIGO);

ALTER TABLE ESPECIES_PLANTAS
ADD CONSTRAINT FK_ESPECIES_PLANTAS_ECOSISTEMAS
FOREIGN KEY (CODIGO_ECOSISTEMA) REFERENCES ECOSISTEMAS(CODIGO);

ALTER TABLE PUBLICACIONES_CIENTIFICAS
ADD CONSTRAINT FK_PUBLICACIONES_CIENTIFICAS_PARQUES_NATURALES
FOREIGN KEY (CODIGO_PARQUE) REFERENCES PARQUES_NATURALES(CODIGO);

ALTER TABLE EQUIPOS_BASICOS
ADD CONSTRAINT FK_EQUIPOS_BASICOS_ACTIVIDADES_PERMITIDAS
FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDADES_PERMITIDAS(ID);

ALTER TABLE ACTIVIDADES_POR_PARQUE
ADD CONSTRAINT FK_ACTIVIDADES_POR_PARQUE
FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDADES_PERMITIDAS(ID);

ALTER TABLE ACTIVIDADES_POR_PARQUE
ADD CONSTRAINT FK_ACTIVIDADES_POR_PARQUE_2
FOREIGN KEY (ID_PARQUE) REFERENCES PARQUES_NATURALES(CODIGO);

ALTER TABLE SERVICIOS
ADD CONSTRAINT FK_SERVICIOS_ACTIVIDADES_PERMITIDAS
FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDADES_PERMITIDAS(ID);

ALTER TABLE RESERVAS
ADD CONSTRAINT FK_RESERVAS_SERVICIOS
FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIOS(ID);

ALTER TABLE RESERVAS
ADD CONSTRAINT FK_RESERVAS_ADULTOS
FOREIGN KEY (ID_ADULTO) REFERENCES ADULTOS(ID_USUARIO);

ALTER TABLE NINIOS
ADD CONSTRAINT FK_NINIOS_PERSONAS
FOREIGN KEY (ID_USUARIO) REFERENCES PERSONAS(ID_USUARIO);

ALTER TABLE ADULTOS
ADD CONSTRAINT FK_ADULTOS_PERSONAS
FOREIGN KEY (ID_USUARIO) REFERENCES PERSONAS(ID_USUARIO);

ALTER TABLE UBICACIONES_POR_PARQUE
ADD CONSTRAINT FK_UBICACIONES_POR_PARQUE_UBICACIONES
FOREIGN KEY (LATITUD, LONGITUD) REFERENCES UBICACIONES(LATITUD, LONGITUD);

ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT FK_DEPARTAMENTOS_UBICACIONES
FOREIGN KEY (LATITUD, LONGITUD) REFERENCES UBICACIONES(LATITUD, LONGITUD);

ALTER TABLE PAISES
ADD CONSTRAINT FK_PAISES_UBICACIONES
FOREIGN KEY (LATITUD, LONGITUD) REFERENCES UBICACIONES(LATITUD, LONGITUD);

-- Unicas

ALTER TABLE PARQUES_NATURALES ADD CONSTRAINT UK_PARQUE
  UNIQUE (NOMBRE);

ALTER TABLE PUBLICACIONES_CIENTIFICAS ADD CONSTRAINT UK_ENLACE
  UNIQUE (ENLACE);

ALTER TABLE ADULTOS ADD CONSTRAINT UK_CONTACTO2
  UNIQUE (CONTACTO);

ALTER TABLE ADULTOS ADD CONSTRAINT UK_CORREO
  UNIQUE (CORREO);

-- Atributos (CK)

ALTER TABLE PARQUES_NATURALES ADD CONSTRAINT CK_TESTADO_PARQUE
CHECK (UPPER(ESTADO) IN ('ABIERTO','CERRADO'));

ALTER TABLE SERVICIOS ADD CONSTRAINT CK_PRECIO_DIA
    CHECK (PRECIO_DIA >= 0);

ALTER TABLE SERVICIOS ADD CONSTRAINT CK_PRECIO_PERSONA
    CHECK (PRECIO_PERSONA >= 0);

ALTER TABLE PARQUES_NATURALES ADD CONSTRAINT CK_CANTIDAD_TRABAJADORES
    CHECK (CANT_TRABAJADORES > 0);

ALTER TABLE PARQUES_NATURALES ADD CONSTRAINT CK_VALOR_INGRESO_ADULTO
    CHECK (VALOR_INGRESO_ADULTOS >= 0 OR VALOR_INGRESO_ADULTOS IS NULL);

ALTER TABLE PARQUES_NATURALES ADD CONSTRAINT CK_VALOR_INGRESO_NINO
    CHECK (VALOR_INGRESO_NINOS >= 0 OR VALOR_INGRESO_NINOS IS NULL);

ALTER TABLE AMENAZAS ADD CONSTRAINT CK_ESTADO_AMENAZA
    CHECK (UPPER(ESTADO) IN ('ACTIVA', 'CONTROLADA', 'EN PROCESO DE MITIGACION', 'EN MONITORIZACION', 'RESUELTA', 'EN EVALUCACION'));

ALTER TABLE AMENAZAS ADD CONSTRAINT CK_TIPO_AMENAZA
    CHECK (UPPER(TIPO) IN ('CAMBIO CLIMATICO', 'INCENDIO FORESTAL', 'CONTAMINACION LUMINICA', 'CONFLICTO HUMANO', 'MINERIA','ACTIVIDAD RECREATIVA', 'INVASION DE ESPECIES EXOTICAS', 'URBANIZACION', 'CAZA','DEFORESTACION'));

ALTER TABLE ECOSISTEMAS ADD CONSTRAINT CK_NOMBRE_ECOSISTEMA
  CHECK (NOMBRE_ECOSISTEMA IN ('BOSQUE TEMPLADO', 'SELVA TROPICAL', 'DESERTO', 'PRADERA', 'TUNDRA', 'ACANTILADO MARINO', 'ARRECIFE DE CORAL',
  'LAGO', 'RIO', 'MANGROVE', 'ESTEPA', 'SABANA', 'BOSQUE CADUCIFOLIO', 'BOSQUE CONIFERO', 'SELVA DE NIEBLA', 'GLACIAR',
  'MARISMA', 'CUEVA', 'OCEANO ABIERTO', 'HUMEDAL', 'BOSQUE DE MANGLE', 'TAIGA', 'BAJO MARINO', 'LAGUNA', 'RIO DE MONTANA',
  'BOSQUE DE ROBLE', 'LAGO DE AGUA SALADA', 'BOSQUE DE BAMBU', 'ISLA VOLCANICA', 'PANTANO', 'ESTUARIO', 'BOSQUE DE SECUCOYA',
  'RIACHUELO', 'PARAMO', 'BOSQUE DE EUCALIPTOS', 'PRAIRIE', 'ISLA CORALINA', 'LAGO DE AGUA DULCE', 'BOSQUE DE CEDROS',
  'VOLCAN SUBMARINO', 'OASIS', 'BOSQUE DE PINOS', 'RIO DE LLANURA', 'VALLE INTERMONTANO', 'BOSQUE DE LAURISILVA',
  'LAGO DE CRATER', 'BOSQUE DE ABETOS', 'LAGO DE MONTANA', 'BOSQUE DE HAYAS', 'ISLA FLUVIAL', 'POZO SUBMARINO', 'CENOTE',
  'BOSQUE DE JUNIPEROS', 'SELVA ESPINOSA', 'LAGO SALINO', 'BOSQUE DE NOGALES', 'LLANURA DE SAL', 'BAJO SALINO',
  'DESIERTO DE HIELO', 'BOSQUE DE KELPIE', 'ESTEPA ARDIENTE', 'LADERA MONTAÑOSA', 'BOSQUE DE CARPINO', 'CHARCA',
  'LAGO ALPINO', 'BOSQUE DE PAPIROS', 'DUNA DE ARENA', 'BOSQUE DE SECUCOYAS', 'BOSQUE DE OLIVOS', 'LAGO CRISTALINO',
  'RIACHUELO', 'PANTANO SALADO', 'POZO SUBMARINO', 'ACANTILADO DE SAL', 'CUEVA SUBMARINA', 'BOSQUE DE PERALES',
  'LAGO GLACIAL', 'BOSQUE DE ALERCES', 'BOSQUE DE MANZANOS', 'LLANURA DE LAVAS', 'BOSQUE DE ACACIAS',
  'OASIS DE AGUA DULCE', 'ISLA DE MAGMA', 'BAJO VOLCANICO', 'LAGO DE AZUFRE', 'BOSQUE DE HIGUERAS', 'BOSQUE DE AVELLANOS',
  'BOSQUE DE FRESNOS', 'DESIERTO DE SALITRE', 'RIO DE AGUAS TERMALES', 'CHARCA DE BARRO', 'BOSQUE DE PERGAMINO',
  'LAGO DE LAVA', 'BOSQUE DE PLATANOS', 'BAJO DE AZUFRE', 'BOSQUE DE CASTAÑOS', 'VALLE DE MANANTIALES', 'LLANURA DE CENIZA',
  'BOSQUE DE HAYAS', 'RIACHUELO DE MIEL', 'ISLA DE NECTAR', 'DESIERTO DE AMBAR', 'BOSQUE DE AMBAR', 'LLANURA DE POLVO',
  'BOSQUE DE JENGIBRE', 'LAGO DE NECTAR', 'BOSQUE DE AMAPOLAS', 'RIACHUELO DE JAZMIN', 'BOSQUE DE PIMIENTA', 'LLANURA DE HIERBABUENA'));

ALTER TABLE AMENAZAS ADD CONSTRAINT CK_GRAVEDAD_AMENAZA
    CHECK (UPPER(GRAVEDAD) IN ('MUY SIGNIFICATIVA', 'POCO SIGNIFICATIVA'));

ALTER TABLE IMPACTOS ADD CONSTRAINT CK_SEVERIDAD_IMPACTO
    CHECK (UPPER(SEVERIDAD) IN ('ALTA', 'MEDIA', 'BAJA'));

ALTER TABLE IMPACTOS ADD CONSTRAINT CK_ACCION_MITIGACION
  CHECK (ACCION_MITIGACION IN ('NINGUNA', 'EN MARCHA', 'PAUSADA', 'CULMINADA'));

ALTER TABLE ECOSISTEMAS ADD CONSTRAINT CK_TIPO_CLIMA
  CHECK (UPPER(CLIMA) IN ('TROPICAL', 'DESIERTO', 'TEMPLADO', 'POLAR', 'BOREAL', 'SUBTROPICAL', 'MEDITERRANEO', 'SEMIARIDO', 'ARIDO', 'TUNDRA'));

ALTER TABLE PUBLICACIONES_CIENTIFICAS ADD CONSTRAINT CK_PALABRA_CLAVE
    CHECK (UPPER(PALABRA_CLAVE) IN ('PARQUE NATURAL','ECOLOGIA','BIODIVERSIDAD','CONSERVACION','IMPACTO AMBIENTAL','ECOSISTEMA','CAMBIO CLIMATICO','TURISMO SOSTENIBLE','RESTAURACION ECOLOGICA','EDUCACION AMBIENTAL','RECURSOS NATURALES','FAUNA','FLORA','AVIFAUNA','REPTILES Y ANFIBIOS','COMUNIDADES INDIGENAS','ARQUEOLOGIA'));

ALTER TABLE PUBLICACIONES_CIENTIFICAS ADD CONSTRAINT CK_TIPO_PUBLICACION
    CHECK (UPPER(TIPO_PUBLICACION) IN ('ARTICULO DE REVISTA CIENTIFICA',  'CAPITULO DE LIBRO','TESIS', 'INFORME TECNICO','PATENTE','MATERIAL DE CONFERENCIA'));

ALTER TABLE PUBLICACIONES_CIENTIFICAS ADD CONSTRAINT CK_ENLACE
    CHECK (REGEXP_LIKE(ENLACE, '^(http|https)://[^\s]+$'));

ALTER TABLE PERSONAS ADD CONSTRAINT CK_GENERO
    CHECK (UPPER(GENERO) IN ('HOMBRE','MUJER','TRANSGENERO','TRANSEXUAL','OTRO'));

ALTER TABLE PERSONAS ADD CONSTRAINT CK_TIPO_DOCUMENTO
    CHECK (UPPER(TIPO_DOCUMENTO) IN ('TI','CC','PPN'));

ALTER TABLE ADULTOS ADD CONSTRAINT CK_CORREO
    CHECK (REGEXP_LIKE(CORREO, '^[^\.@]+@[^\.@]+\.[^\.@]+$'));

ALTER TABLE NINIOS ADD CONSTRAINT CK_RH
    CHECK (UPPER(RH) IN ('A+','A-','B+','B-','AB+','AB-','O+','O-'));

ALTER TABLE NINIOS ADD CONSTRAINT CK_ARCHIVO
    CHECK (CARNET_VACUNAS LIKE ('%.pdf'));

ALTER TABLE NINIOS ADD CONSTRAINT CK_CONSENTIMIENTO
    CHECK (CONSENTIMIENTO LIKE ('%.pdf'));

ALTER TABLE RESERVAS ADD CONSTRAINT CK_PAGADO
    CHECK (UPPER(PAGADO) IN ('1','0'));

ALTER TABLE RESERVAS ADD CONSTRAINT CK_ESTADO_RESERVA
    CHECK (UPPER(ESTADO) IN ('ACEPTADA','RECHAZADA','PENDIENTE'));

ALTER TABLE SERVICIOS ADD CONSTRAINT CK_MAYOR_DE_EDAD
    CHECK (UPPER(MAYOR_DE_EDAD) IN ('1','0'));

ALTER TABLE ACTIVIDADES_PERMITIDAS ADD CONSTRAINT CK_TIPO_ACTIVIDAD
  CHECK (UPPER(TIPO_DE_ACTIVIDAD) IN ('MONTANISMO', 'OBSERVACION AVES', 'SENDERISMO TERRESTRE', 'OBSERVACION GEOLOGICA', 'OBSERVACION FAUNA Y FLORA', 'INVESTIGACION EDUCACION AMBIENTAL', 'FOTOGRAFIA NO COMERCIAL', 'CICLOMONTANISMO', 'OBSERVACION ESTELAR', 'PESCA'));

ALTER TABLE EQUIPOS_BASICOS  ADD CONSTRAINT CK_TIPO_EQUIPO
  CHECK (UPPER(NOMBRE_EQUIPO) IN ('GAFAS CON PROTECCION ULTRAVIOLETA', 'BLOQUEADOR SOLAR', 'LINTERNA FRONTAL', 'MORRAL PEQUENO', 'ROPA IMPERMEABLE Y ABRIGADA', 'CANTIMPLORA', 'BOLSA PARA RETORNAR LA BASURA', 'ALIMENTOS LIGEROS'));

ALTER TABLE UBICACIONES ADD CONSTRAINT CK_TIPO_UBICACION
    CHECK (TAMANO > 0);

-- Consultas
SELECT 
  p.codigo AS codigo_parque,
  p.nombre AS nombre_parque,
  e.codigo AS codigo_ecosistema,
  e.nombre_ecosistema AS nombre_ecosistema
FROM PARQUES_NATURALES p JOIN ECOSISTEMAS e ON p.codigo = e.codigo_parque;

SELECT
  p.codigo AS codigo_parque,
  p.nombre AS nombre_parque,
  ec.nombre_ecosistema AS nombre_ecosistema,
  ec.clima AS clima
FROM
  PARQUES_NATURALES p
JOIN
  ECOSISTEMAS ec ON p.codigo = ec.codigo_parque
ORDER BY clima;

SELECT 
    a.codigo AS codigo_amenaza,
    a.tipo AS tipo_amenaza,
    e.nombre_especie
FROM 
    AMENAZAS a
JOIN
    IMPACTOS i ON a.codigo = i.codigo_amenaza
JOIN
    ESPECIES_AFECTADAS e ON e.codigo_amenaza = i.codigo_amenaza;

SELECT
    p.codigo AS codigo_parque,
    p.nombre AS nombre_parque,
    pu.id AS id_publicacion,
    pu.titulo AS titulo_publicacion,
    pu.palabra_clave AS palabra_clave_publicacion
FROM
    PUBLICACIONES_CIENTIFICAS pu
JOIN
    PARQUES_NATURALES p ON pu.codigo_parque = p.codigo
ORDER BY
palabra_clave_publicacion;

SELECT
  p.codigo AS codigo_parque,
  p.nombre AS nombre_parque,
  s.id AS id_servicio,
  s.tipo_servicio,
  s.precio_dia,
  s.precio_persona,
  CASE WHEN s.mayor_de_edad = 1 THEN 'Si' WHEN s.mayor_de_edad = 0 THEN 'No' END AS necesita_mayor_de_edad
FROM
    SERVICIOS s
JOIN 
    ACTIVIDADES_PERMITIDAS ac ON s.id_actividad = ac.id
JOIN
    ACTIVIDADES_POR_PARQUE acp ON acp.id_actividad = ac.id
JOIN
    PARQUES_NATURALES p ON p.codigo = acp.id_parque;

SELECT
  p.codigo AS codigo_parque,
  p.nombre AS nombre_parque,
  ac.id AS id_actividad,
  ac.tipo_de_actividad AS tipo_de_actividad
FROM
    ACTIVIDADES_PERMITIDAS ac
JOIN
    ACTIVIDADES_POR_PARQUE acp ON acp.id_actividad = ac.id
JOIN
    PARQUES_NATURALES p ON p.codigo = acp.id_parque;


SELECT 
    ea.nombre_comun,
    ea.nombre_cientifico,
    p.nombre AS nombre_parque
FROM
    ESPECIES_ANIMALES ea
JOIN
    ECOSISTEMAS e ON ea.codigo_ecosistema = e.codigo
JOIN
    PARQUES_NATURALES p ON p.codigo = e.codigo_parque
ORDER BY
    nombre_parque;

SELECT 
    ea.nombre_comun,
    ea.nombre_cientifico,
    p.nombre AS nombre_parque
FROM
    ESPECIES_PLANTAS ea
JOIN
    ECOSISTEMAS e ON ea.codigo_ecosistema = e.codigo
JOIN
    PARQUES_NATURALES p ON p.codigo = e.codigo_parque
ORDER BY
    nombre_parque;

SELECT
  p.nombre AS nombre_parque,
  r.id_adulto AS usuario,
  r.pagado,
  a.tipo_de_actividad AS actividad,
  r.precio_total AS valor,
  r.estado
FROM
  RESERVAS r
JOIN
  SERVICIOS s ON r.id_servicio = s.id
JOIN
  ACTIVIDADES_PERMITIDAS a ON s.id_actividad = a.id
JOIN
  ACTIVIDADES_POR_PARQUE ap ON ap.id_actividad = a.id
JOIN
  PARQUES_NATURALES p ON p.codigo = ap.id_parque
ORDER BY
  nombre_parque;

SELECT
  PN.CODIGO AS CODIGO_PARQUE,
  PN.NOMBRE AS nombre_parque,
  S.ID AS ID_SERVICIO,
  COUNT(R.NUMERO) AS NUMERO_DE_RESERVAS
FROM
  PARQUES_NATURALES PN
  JOIN SERVICIOS S ON PN.CODIGO = S.ID_ACTIVIDAD
  LEFT JOIN RESERVAS R ON S.ID = R.ID_SERVICIO
GROUP BY
  PN.CODIGO, PN.NOMBRE, S.ID, S.DESCRIPCION
ORDER BY
  NUMERO_DE_RESERVAS DESC;

SELECT
  p.codigo AS codigo_parque,
  p.nombre AS nombre_parque,
  ac.id AS id_actividad,
  ac.tipo_de_actividad AS tipo_de_actividad,
  s.ID AS id_servicio,
  pa.nombre AS nombre_pais,
  d.nombre AS nombre_departamento
FROM
    ACTIVIDADES_PERMITIDAS ac
JOIN
    ACTIVIDADES_POR_PARQUE acp ON acp.id_actividad = ac.id
JOIN
    PARQUES_NATURALES p ON p.codigo = acp.id_parque
JOIN
    SERVICIOS s ON s.ID_ACTIVIDAD = ac.ID
JOIN
    UBICACIONES_POR_PARQUE up ON up.codigo_parque = p.codigo 
JOIN
    UBICACIONES u ON u.latitud = up.latitud AND u.longitud = up.longitud
JOIN
    PAISES pa ON u.latitud = pa.latitud AND u.longitud = pa.longitud
JOIN
    DEPARTAMENTOS d ON u.latitud = d.latitud AND u.longitud = d.longitud;

/*
-- Poblar NoOk
--- Tipos de datos
INSERT INTO NINIOS (ID_USUARIO, RH, RESPONSABLE, CARNET_VACUNAS, ESTATURA, CONSENTIMIENTO) 
VALUES ('Usuario123', 'Cualquier Cosa', 'Papa123', 'vacuna.pdf', 1123123.9, 'consentimiento.pdf');
--- PK, FK, UK

--Va a dejar insertar 1 pero el segundo no por la restriccion de PK
INSERT INTO PARQUES_NATURALES (CODIGO, NOMBRE, HORA_APERTURA, HORA_CIERRE, CANT_TRABAJADORES, FECHA_REGISTRO) 
VALUES ('1', 'Parque123', SYSDATE, SYSDATE, 10, SYSDATE);

INSERT INTO PARQUES_NATURALES (CODIGO, NOMBRE, HORA_APERTURA, HORA_CIERRE, CANT_TRABAJADORES, FECHA_REGISTRO) 
VALUES ('1', 'Parque123', SYSDATE, SYSDATE, 10, SYSDATE);

INSERT INTO AMENAZAS_POR_PARQUE (CODIGO_PARQUE, CODIGO_AMENAZA) 
VALUES ('Cualquier Cosa', 'Cualquier Cosa');

INSERT INTO PARQUES_NATURALES (CODIGO, NOMBRE, HORA_APERTURA, HORA_CIERRE, CANT_TRABAJADORES, FECHA_REGISTRO) 
VALUES ('3', 'Parque123', SYSDATE, SYSDATE, 15, SYSDATE);
--- Checks
INSERT INTO PARQUES_NATURALES (CODIGO, NOMBRE, HORA_APERTURA, HORA_CIERRE, CANT_TRABAJADORES, FECHA_REGISTRO,VALOR_INGRESO_ADULTOS,VALOR_INGRESO_NINOS) 
VALUES ('1', 'Parque1', SYSDATE, SYSDATE, -5,SYSDATE,2,3);

INSERT INTO PARQUES_NATURALES (CODIGO, NOMBRE, HORA_APERTURA, HORA_CIERRE, CANT_TRABAJADORES, FECHA_REGISTRO,VALOR_INGRESO_ADULTOS,VALOR_INGRESO_NINOS) 
VALUES ('1', 'Parque1', SYSDATE, SYSDATE,8,SYSDATE,-3,3);

INSERT INTO PARQUES_NATURALES (CODIGO, NOMBRE, HORA_APERTURA, HORA_CIERRE, CANT_TRABAJADORES, FECHA_REGISTRO,VALOR_INGRESO_ADULTOS,VALOR_INGRESO_NINOS) 
VALUES ('1', 'Parque1', SYSDATE, SYSDATE,8,SYSDATE,3,-3);

INSERT INTO AMENAZAS (CODIGO, ESTADO, GRAVEDAD, TIPO, FECHA_DETECCION, FECHA_MITIGACION) 
VALUES ('1', 'Cualquier Cosa', 'MUY SIGNIFICATIVA', 'CAMBIO CLIMATICO', SYSDATE, SYSDATE);

INSERT INTO ACTIVIDADES_PERMITIDAS (ID, DESCRIPCION_ACTIVIDAD, TIPO_DE_ACTIVIDAD) 
VALUES ('1', 'Descripcion', 'Cualquier cosa');

INSERT INTO EQUIPOS_BASICOS (ID, ID_ACTIVIDAD, NOMBRE_EQUIPO) 
VALUES ('1', 'Actividad123', 'Cualquier Cosa');

INSERT INTO RESERVAS (NUMERO, ID_SERVICIO, ID_ADULTO, FECHA_RESERVACION, PAGADO, CANTIDAD_PERSONAS, CONTACTO, ESTADO, FECHA_ASISTENCIA) 
VALUES ('2', 'Servicio123', 'Usuario123',SYSDATE, 2, 3, 'user@example.com', 'Cualquier Cosa', SYSDATE);

INSERT INTO PERSONAS (ID_USUARIO, NOMBRE, FECHA_NACIMIENTO, GENERO, DOCUMENTO_IDENTIFICACION, TIPO_DOCUMENTO) 
VALUES ('User789', 'John Doe', SYSDATE, 'Cualquier Cosa', '123456789', 'TI');

INSERT INTO NINIOS (ID_USUARIO, RH, RESPONSABLE, CARNET_VACUNAS, ESTATURA, CONSENTIMIENTO) 
VALUES ('Usuario123', 'Cualquier Cosa', 'Papa123', 'vacuna.pdf', 1.99, 'consentimiento.pdf');

INSERT INTO NINIOS (ID_USUARIO, RH, RESPONSABLE, CARNET_VACUNAS, ESTATURA, CONSENTIMIENTO) 
VALUES ('Usuario123', 'A+', 'Papa123', 'Cualquier Cosa.doc', 1.2, 'consentimiento.pdf');

INSERT INTO NINIOS (ID_USUARIO, RH, RESPONSABLE, CARNET_VACUNAS, ESTATURA, CONSENTIMIENTO) 
VALUES ('Usuario123', 'A+', 'Papa123', 'vacunas.pdf', 1.2, 'Cualquier Cosa.doc');

INSERT INTO UBICACIONES (LATITUD, LONGITUD, TAMANO) 
VALUES (40.7128, -74.0060, 0);

INSERT INTO ADULTOS (ID_USUARIO, PAIS_RESIDENCIA, CONTACTO, CORREO) 
VALUES ('usuario123', 'pais123', 'contacto123', 'Cualquier Cosa@example');

INSERT INTO PUBLICACIONES_CIENTIFICAS (ID, CODIGO_PARQUE, TITULO, FECHA_PUBLICACION, PALABRA_CLAVE, ENLACE, TIPO_PUBLICACION, FECHA_REGISTRO, AUTOR) 
VALUES ('2', 'parque123', 'titulo', SYSDATE, 'Cualquier Cosa', 'http://ejemplo.com', 'articulo', SYSDATE, 'Sebastian');

INSERT INTO PUBLICACIONES_CIENTIFICAS (ID, CODIGO_PARQUE, TITULO, FECHA_PUBLICACION, PALABRA_CLAVE, ENLACE, TIPO_PUBLICACION, FECHA_REGISTRO, AUTOR) 
VALUES ('2', 'parque123', 'titulo', SYSDATE, 'Cualquier Cosa', 'http://ejemplo.com', 'Cualquier Cosa', SYSDATE, 'Sebastian');

INSERT INTO PARQUES_NATURALES (CODIGO, NOMBRE, HORA_APERTURA, HORA_CIERRE, CANT_TRABAJADORES, FECHA_REGISTRO) 
VALUES ('3', 'parque3', SYSDATE, SYSDATE, 0, SYSDATE);

INSERT INTO PARQUES_NATURALES (CODIGO, NOMBRE, HORA_APERTURA, HORA_CIERRE, CANT_TRABAJADORES, FECHA_REGISTRO, VALOR_INGRESO_ADULTOS) 
VALUES ('4', 'parque4', SYSDATE, SYSDATE, 20, SYSDATE, -10);

INSERT INTO PARQUES_NATURALES (CODIGO, NOMBRE, HORA_APERTURA, HORA_CIERRE, CANT_TRABAJADORES, FECHA_REGISTRO, VALOR_INGRESO_NINOS) 
VALUES ('5', 'Park5', SYSDATE, SYSDATE, 25, SYSDATE, -5);

INSERT INTO IMPACTOS (CODIGO_AMENAZA, DESCRIPCION, ACCION_MITIGACION, SEVERIDAD) 
VALUES ('amenaza123', 'descripcion', 'Cualquier Cosa', 'ALTA');
*/

--- X Poblar
DELETE FROM RESERVAS;
DELETE FROM SERVICIOS;
DELETE FROM ACTIVIDADES_POR_PARQUE;
DELETE FROM EQUIPOS_BASICOS;
DELETE FROM PUBLICACIONES_CIENTIFICAS;
DELETE FROM ESPECIES_PLANTAS;
DELETE FROM ESPECIES_ANIMALES;
DELETE FROM ESPECIES_AFECTADAS;
DELETE FROM IMPACTOS;
DELETE FROM AMENAZAS_POR_PARQUE;
DELETE FROM CONTACTOS_PARQUE;
DELETE FROM UBICACIONES_POR_PARQUE;
DELETE FROM ECOSISTEMAS;
DELETE FROM UBICACIONES;
DELETE FROM NINIOS;
DELETE FROM ADULTOS;
DELETE FROM PERSONAS;
DELETE FROM DEPARTAMENTOS;
DELETE FROM PAISES;
DELETE FROM AMENAZAS_POR_PARQUE;
DELETE FROM ACTIVIDADES_PERMITIDAS;
DELETE FROM PARQUES_NATURALES;