DROP SEQUENCE SEQ_MI_VALOR_UNICO;
DROP SEQUENCE SEQ_MI_VALOR_UNICO2;
DROP SEQUENCE SEQ_MI_VALOR_UNICO3;
DROP SEQUENCE SEQ_MI_VALOR_UNICO4;
DROP SEQUENCE SEQ_MI_VALOR_UNICO5;
DROP SEQUENCE SEQ_MI_VALOR_UNICO6;
DROP SEQUENCE SEQ_MI_VALOR_UNICO7;
DROP SEQUENCE SEQ_MI_VALOR_UNICO8;
DROP SEQUENCE SEQ_MI_VALOR_UNICO9;
DROP SEQUENCE SEQ_MI_VALOR_UNICO10;
DROP SEQUENCE SEQ_MI_VALOR_UNICO11;
DROP SEQUENCE SEQ_MI_VALOR_UNICO12;
DROP SEQUENCE SEQ_MI_VALOR_UNICO13;
DROP SEQUENCE SEQ_MI_VALOR_UNICO14;
DROP SEQUENCE SEQ_MI_VALOR_UNICO15;
DROP SEQUENCE SEQ_MI_VALOR_UNICO16;
DROP SEQUENCE SEQ_MI_VALOR_UNICO17;
DROP SEQUENCE SEQ_MI_VALOR_UNICO18;
DROP SEQUENCE SEQ_MI_VALOR_UNICO19;
DROP SEQUENCE SEQ_MI_VALOR_UNICO20;


CREATE SEQUENCE SEQ_MI_VALOR_UNICO
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO2
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO3
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO4
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO5
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO6
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO7
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO8
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO9
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO10
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO11
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO12
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO13
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO14
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO15
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO16
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO17
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO18
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO19
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;

CREATE SEQUENCE SEQ_MI_VALOR_UNICO20
 MINVALUE 1
 START WITH 1
 INCREMENT BY 1
 CACHE 100;